### ISSUE TITLE
Error when Self Hosting

### ISSUE THREAD

**Issue by matthawk60** [calcom/synclinear.com#74]
```
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
at new NodeError (node:internal/errors:387:5)
at prepareSecretKey (node:internal/crypto/keys:584:11)
at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
at new Cipheriv (node:internal/crypto/cipher:243:3)
at createCipheriv (node:crypto:138:10)
at encrypt (/app/.next/server/pages/api/save.js:56:70)
at handle (/app/.next/server/pages/api/save.js:156:66)
at Object.apiResolver (/app/node_modules/.pnpm/next@12.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/api-utils/node.js:366:15)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:469:9) {
code: 'ERR_INVALID_ARG_TYPE'
}
```

I'm unable to self host the app at all.  This error is displayed when I try to hook up linear and gihub.  

The github webhook is created but throws this error:

{"success":false,"message":"Could not find issue's corresponding team."}

**Comment by tedspare** [comment]
Hi @matthawk60. The error message `"key" argument must be of type string` indicates the DB is missing a GitHub API key ([see schema](https://github.com/calcom/synclinear.com/blob/main/prisma/schema.prisma#L72)). Could you try re-syncing and see if this gets populated or, otherwise, share any error messages in the browser? Thanks.

**Comment by sanderpick** [comment]
I'm seeing this as well. I have it setup to use the OAuth flow. In this case, where does the Github Key come from? Do I need to create an all-powerful GK personal access token and set it as the `GITHUB_API_KEY` env var?

**Comment by sanderpick** [comment]
Ah, the "key" is an encryption key as an env var. 32 bytes. I tweaked the logic to expect the key as a base64 encoded string: https://github.com/tablelandnetwork/synclinear.com/commit/ac99b6855ddbdbea007176d31a095ff81ad0f84e

I think the railway template needs to include `ENCRYPTION_KEY` as a variable. I've added it manually... so far so good.
